name: meteoapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_splash_screen: ^1.3.0
  animations: ^2.0.8
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase: ^9.0.3
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.10
  fluentui_system_icons: ^1.1.222
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.0.0
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_animations: ^0.3.0
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.4
  formz: ^0.6.1
  geocoding: ^2.2.0
  geolocator: ^10.1.0
  geolocator_android: ^4.4.1
  geolocator_apple: ^2.3.5
  get_it: ^7.6.0
  google_maps_flutter: ^2.3.0
  http: ^0.13.6
  hydrated_bloc: ^9.1.3
  image_picker: ^1.0.4
  intl: ^0.17.0
  is_first_run: ^1.0.0
  latlong2: ^0.8.2
  location: ^5.0.3
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.2
  simple_animations: ^3.2.0
  timezone: ^0.9.2
  weather_animation: ^1.0.1
  widget_circular_animator: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Chillax
      fonts:
        - asset: assets/fonts/chillax/Chillax-Regular.ttf
        - asset: assets/fonts/chillax/Chillax-Bold.ttf

    - family: Excon
      fonts:
        - asset: assets/fonts/excon/Excon-Regular.ttf
        - asset: assets/fonts/excon/Excon-Bold.ttf

    - family: BespokeSerif
      fonts:
        - asset: assets/fonts/bespoke_sheriff/BespokeSerif-Regular.ttf
        - asset: assets/fonts/bespoke_sheriff/BespokeSerif-Light.ttf
        - asset: assets/fonts/bespoke_sheriff/BespokeSerif-Italic.ttf

flutter_native_splash:
  color: "#071b5d"
  image: assets/splash.png
  fill: true
  android: true
  ios: true
  color_dark: "#000000"
  android_12:
    image: assets/sun12.png
